name = "ComplexOperations"
uuid = "45c10c9a-3fea-40aa-8a0f-0e2f7025918e"
authors = ["Mahmoud Elzouka <mhmodzoka@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.0"
StaticArrays = "1.2.2"